#!/usr/bin/env python3
"""Generate the Codex, Cursor and Gemini CLI subagents from the Claude Code ones (single source of truth).

    python3 scripts/gen_harness.py          # rewrite kit/.codex/agents, kit/.cursor/agents, kit/.gemini/agents
    python3 scripts/gen_harness.py --check  # CI: exit 1 if the generated files are stale

Tiers are harness-neutral (fast / balanced / strong). Change a model in TIERS, run this, commit.
Model IDs verified on 2026-10-09: Claude docs, learn.chatgpt.com/docs/models, cursor.com/docs/subagents,
geminicli.com/docs/core/subagents. Keep this table and .uak/docs/ORCHESTRATION.md in sync.
"""
import re
import sys
from pathlib import Path

KIT = Path(__file__).resolve().parents[1] / "kit"
CLAUDE_TIER = {"haiku": "fast", "sonnet": "balanced", "opus": "strong"}
TIERS = {
    # tier:    (codex model, codex effort, cursor model, gemini model)
    "fast": ("gpt-6-luna", "low", "composer-2.5", "gemini-3-flash-preview"),
    "balanced": ("gpt-6.1-sol", "medium", "inherit", "inherit"),
    "strong": ("gpt-6-astra", "high", "claude-opus-5-5[effort=high]", "gemini-3-pro-preview"),
}
GEMINI_READ = ["read_file", "read_many_files", "grep_search", "glob", "list_directory"]
HEADER = "Generated by scripts/gen_harness.py from .claude/agents/{name}.md; edit that file, not this one."


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    meta = {}
    for line in m.group(1).splitlines():
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip()
    return meta, m.group(2).strip() + "\n"


def readonly(meta):
    return "Edit" in meta.get("disallowedTools", "")


def toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def codex(meta, body, tier):
    model, effort, _, _ = TIERS[tier]
    effort = {"low": "low", "medium": "medium", "high": "high"}.get(meta.get("effort", ""), effort)
    sandbox = "read-only" if readonly(meta) else "workspace-write"
    body = body.rstrip()
    return "\n".join([
        "# " + HEADER.format(name=meta["name"]),
        f"name = {toml_str(meta['name'])}",
        f"description = {toml_str(meta['description'])}",
        f"model = {toml_str(model)}",
        f"model_reasoning_effort = {toml_str(effort)}",
        f"sandbox_mode = {toml_str(sandbox)}",
        'developer_instructions = """',
        body.replace('"""', "'''"),
        '"""',
        "",
    ])


def cursor(meta, body, tier):
    model = TIERS[tier][2]
    lines = ["---", f"name: {meta['name']}", f"description: {meta['description']}", f"model: {model}"]
    if readonly(meta):
        lines.append("readonly: true")
    lines += ["---", f"<!-- {HEADER.format(name=meta['name'])} -->", body]
    return "\n".join(lines)


def gemini(meta, body, tier):
    model = TIERS[tier][3]
    # Read-only agents with Bash keep the shell: their prompt limits it to read-only commands.
    tools = GEMINI_READ + (["run_shell_command"] if "Bash" in meta.get("tools", "") else [])
    if not readonly(meta):
        tools += ["write_file", "replace"]
    turns = meta.get("maxTurns", "15")
    lines = ["---", f"name: {meta['name']}", f"description: {meta['description']}", "kind: local",
             "tools:"] + [f"  - {t}" for t in tools] + [f"model: {model}", f"max_turns: {turns}", "timeout_mins: 10",
             "---", f"<!-- {HEADER.format(name=meta['name'])} -->", body]
    return "\n".join(lines)


NEUTRAL = [("on Haiku", "on the fast model"), ("Haiku", "fast-model"), ("Opus", "strong-model"), ("Sonnet", "balanced-model")]


def neutral(text):
    for a, b in NEUTRAL:
        text = text.replace(a, b)
    return text


def main():
    check = "--check" in sys.argv
    out = {}
    for src in sorted((KIT / ".claude/agents").glob("*.md")):
        meta, body = parse(src)
        tier = CLAUDE_TIER.get(meta.get("model", ""), "balanced")
        meta = {**meta, "description": neutral(meta["description"])}
        body = neutral(body)
        tier = CLAUDE_TIER.get(meta.get("model", ""), "balanced")
        name = meta["name"]
        out[KIT / f".codex/agents/{name}.toml"] = codex(meta, body, tier)
        out[KIT / f".cursor/agents/{name}.md"] = cursor(meta, body, tier)
        out[KIT / f".gemini/agents/{name}.md"] = gemini(meta, body, tier)
    stale = [p for p, t in out.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
    if check:
        for p in stale:
            print("stale:", p.relative_to(KIT.parent))
        return 1 if stale else 0
    for p, t in out.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(t, encoding="utf-8")
    print(f"wrote {len(out)} files ({len(stale)} changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
